project_name: github.com/platform-horizon/ghealth

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: "{{ .ProjectName }}-{{ .Version }}"
  - skip: true
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags: -s -w -X main.versionNumber={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.author={{ .Env.Author }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
