name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and test on go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
       matrix:
         go_version: [1.17]
  
    steps:
      - name: Install Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ^${{ matrix.go_version }}
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Publish
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}