name: build

# on:
#   push:
#     tags:
#       - '*'
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and test on go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
       matrix:
         go_version: [1.17]
  
    steps:
      - name: Install Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ^${{ matrix.go_version }}
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Go Version
        run: go version

      - name: Go Dependencies
        run: go get -v -t -d ./...

      - name: Go Test
        run: go test -v -coverprofile=profile.cov ./...

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./profile.cov

      - name: Build
        if: matrix.go_version == ${{ matrix.go_version }}
        run: go build -v ./...
      
      # - name: Publish
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     distribution: goreleaser
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}